[tool.poetry]
name = "gatech-aws-credentials"
version = "1"
description = "Retrieve credentials for Georgia Tech AWS accounts using CAS"
license = "MIT"
authors = ["Kristaps Berzinch <kristapsberzinch@gmail.com>"]
repository = "https://github.com/RoboJackets/gatech-aws-credentials"

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.23.0"
boto3 = "^1.12.11"
beautifulsoup4 = "^4.8.2"
keyring = "^21.2.1"

[tool.poetry.dev-dependencies]
boto3-stubs = "*"
black = "^19.10b0"
flake8 = "^3.8.3"
pylint = "^2.5.3"
mypy = "^0.782"

[tool.poetry.scripts]
gatech-aws-credentials = 'gatech_aws_credentials:main'

[tool.black]
line-length = 100
target-version = ['py38']

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
