[tool.poetry]
name = "gatech-aws-credentials"
version = "4"
description = "Retrieve credentials for Georgia Tech AWS accounts using CAS"
license = "MIT"
authors = ["Kristaps Berzinch <kristapsberzinch@gmail.com>"]
repository = "https://github.com/RoboJackets/gatech-aws-credentials"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.23.0"
boto3 = "^1.12.11"
beautifulsoup4 = "^4.8.2"
keyring = "^21.2.1"

[tool.poetry.dev-dependencies]
black = "^23"
boto3-stubs = "^1"
botostubs = "^0.15"
flake8 = "^7"
flake8-bugbear = "^23"
flake8-import-order = "^0.18"
mypy = "^1"
pylint = "^3"

[tool.poetry.scripts]
gatech-aws-credentials = 'gatech_aws_credentials:main'

[tool.poetry.group.dev.dependencies]
types-requests = "^2.31.0.20240106"

[tool.black]
line-length = 100
target-version = ['py38']

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
