[tool.poetry]
name = "gatech-aws-credentials"
version = "2"
description = "Retrieve credentials for Georgia Tech AWS accounts using CAS"
license = "MIT"
authors = ["Kristaps Berzinch <kristapsberzinch@gmail.com>"]
repository = "https://github.com/RoboJackets/gatech-aws-credentials"

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.23.0"
boto3 = "^1.12.11"
beautifulsoup4 = "^4.8.2"
keyring = "^21.2.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
boto3-stubs = "*"
botostubs = "*"
flake8 = "*"
flake8-black = "*"
flake8-bugbear = "*"
flake8-import-order = "*"
flake8-json = "*"
mypy = "*"
pylint = "*"

[tool.poetry.scripts]
gatech-aws-credentials = 'gatech_aws_credentials:main'

[tool.black]
line-length = 100
target-version = ['py38']

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
